---
title: "Report Templates"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Report Templates}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette illustrates the available report template layouts in `templates.R`.

```{r}
require(mapvizieR)
require(grid)
require(dplyr)

knitr::opts_chunk$set(
  dev = 'svg',
  fig.width = 5,
  fig.height = 3
)

p01 <- grobTree(
  rectGrob(gp=gpar(fill='orange', alpha=0.9)), textGrob('p01')
)
p02 <- grobTree(
  rectGrob(gp=gpar(fill='gray', alpha=0.9)), textGrob('p02')
)
p03 <- grobTree(
  rectGrob(gp=gpar(fill='pink', alpha=0.9)), textGrob('p03')
)
p04 <- grobTree(
  rectGrob(gp=gpar(fill='blue', alpha=0.9)), textGrob('p04')
)
p05 <- grobTree(
  rectGrob(gp=gpar(fill='red', alpha=0.9)), textGrob('p05')
)
p06 <- grobTree(
  rectGrob(gp=gpar(fill='green', alpha=0.9)), textGrob('p06')
)

```

## template 01

Template 01 is a 2 column grid.
```{r}

template_01(p01, p02) %>% grid.draw()

```

## template 02

Template 02 is a 3 column grid.
```{r}

template_02(p01, p02, p03) %>% grid.draw()

```


## template 03

Template 03 is a 2 x 2 column grid.
```{r}

template_03(p01, p02, p03, p04) %>% grid.draw()

```

## template 04

Template 04 is a 3 column grid, focused on the center, with 2 row grids on each side.
```{r}

template_04(p01, p02, p03, p04, p05) %>% grid.draw()

```

## template 05

Template 05 is a 2 *row* grid.
```{r}

template_05(p01, p02) %>% grid.draw()

```

## template 06

Template 05 is a 2 column grid.
```{r}

template_06(p01, p02, p03, p04, p05, p06) %>% grid.draw()

```