utils::globalVariables(
  c("%>%", ".", "..y..", "accel_growth", "accel_growth.x", "accel_growth.y",
    "act", "act_df", "active_percentile", "aes", "annotate", "approx_grade",
    "avg_end_rit", "avg_start_rit", "avg_y_dummy", "base_rit", "baseline_color",
    "cdf", "cgi", "cgp", "cgp_helper", "cgp_label", "class_name", "cohort",
    "cohort_season", "cohort_status_npr", "cohort_year", "collapse_schools",
    "color_identity", "complete_obsv", "consistent_percentile",
    "consistent_percentile.x", "consistent_percentile.y", "coord_cartesian",
    "coord_flip", "count", "count_label", "detail_academic_year", "diff_pctl",
    "diff_rit", "diff_rit_bool", "diff_rit_neg_pos", "diff_rit_se",
    "dummy_group", "dummy_rit", "dummy_x", "element_blank", "element_line",
    "element_rect", "element_text", "end_cohort_status_npr",
    "end_consistent_percentile", "end_fallwinterspring", "end_grade",
    "end_grade_level_season", "end_map_year_academic", "end_mean_npr",
    "end_mean_rit", "end_mean_testritscore", "end_n_50th_pctl", "end_n_75th_pctl",
    "end_percentile", "end_rit", "end_schoolname", "End_Season", "end_testid",
    "end_testpercentile", "end_testritscore", "endpoint_color",
    "ex_CombinedAssessmentResults", "ex_CombinedStudentsBySchool",
    "facet_format", "facet_grid", "facet_wrap", "fake_kipp_data",
    "FallToFallProjectedGrowth", "fallwinterspring", "filter_by", "first_rn",
    "for_filter", "geom_bar", "geom_boxplot", "geom_density", "geom_histogram",
    "geom_hline", "geom_jitter", "geom_line", "geom_point", "geom_segment",
    "geom_text", "geom_vline", "ggplot", "ggplot_build", "ggtitle",
    "goal_color", "goal_high", "goal_low", "goal_name", "goal_score",
    "goal_status", "goal_stderr", "goal1name", "goal1range", "goal1ritscore",
    "goal1stderr", "goal2name", "goal2ritscore", "goal3name", "goal3ritscore",
    "goal4name", "goal4ritscore", "goal5name", "goal5ritscore", "goal6name",
    "goal6ritscore", "goal7name", "goal7ritscore", "goal8name", "goal8range",
    "goal8ritscore", "goal8stderr", "grade", "grade_level_season",
    "grade_season_label", "grade_seq", "grade_year", "group", "group_label",
    "Growth_Academic_Year", "growth_color_identity", "growth_df",
    "Growth_Grade_Level", "growth_status", "growth_status_rank", "growth_status2",
    "growth_target", "growth_window", "GrowthMeasureYN", "guides", "helper",
    "highlight_me", "hilite", "id", "implicit_cohort", "include",
    "interpolate_flag", "is_highlight", "is_preferred", "iter", "join_id",
    "kipp_tiered_growth", "label", "label_disp", "label_pos", "label_text",
    "label1_text", "label2_text", "labs", "lag", "last_rn", "lead", "loc",
    "map_year_academic", "mapviz", "mapviz_midyear", "matches", "max_extent",
    "max_extent_rit", "max_grade_level_season", "mean_cgi", "mean_high",
    "mean_low", "mean_npr", "mean_rit", "mean_score", "mean_testritscore",
    "measurementscale", "met_accel_growth", "met_accel_growth.x",
    "met_accel_growth.y", "met_typical_growth", "midpoint", "min_extent",
    "min_extent_rit", "min_grade_level_season", "mutate", "n", "n_accel_growth",
    "n_negative", "n_quartile", "n_students", "n_total", "n_typ_false",
    "n_typ_true", "n_typical", "na_flag", "name", "name_helper", "name_x",
    "neg_flag", "next_rit", "next_testid", "no_labs", "npr_change", "num_valid",
    "ny_grade", "ny_predicted_proficiency", "ny_rit", "ny_season", "ny_subj",
    "offset", "one_of", "pancakes", "pct", "pct_above", "Perc_Growth",
    "percent", "PercentCorrect", "position_jitter", "prepped_cdf",
    "prepped_roster", "processed_cdf", "ProjectedProficiency",
    "ProjectedProficiencyLevel3", "ProjectedProficiencyStudy1", "quartile",
    "quartile_label_pos", "quartile_type", "Rank2", "rank_asc", "rank_desc",
    "rank_npr_least", "rank_npr_most", "rel", "report_measurementscale",
    "report_schooltype", "reported_growth", "rit", "RIT", "rit_change",
    "rit_growth", "rit_hjust", "rit_xoffset", "RITtoReadingScore", "rn_down",
    "rn_ho", "rn_up", "roster", "row_number", "row_type", "rowids",
    "scale_alpha_discrete", "scale_color_identity", "scale_color_manual",
    "scale_fill_brewer", "scale_fill_identity", "scale_fill_manual",
    "scale_size_identity", "scale_x_continuous", "scale_y_continuous",
    "sch_growth_norms_2012", "sch_growth_norms_2015", "School_Display_Name",
    "school_percentile", "school_status_norms_2015_dense_extended",
    "schoolname", "season", "sgp", "short_name", "signed_growth_target",
    "size_scaled", "SpringToSpringConditionalGrowthPercentile",
    "start_cohort_status_npr", "start_consistent_percentile",
    "start_fallwinterspring", "start_fws_prefer", "start_grade",
    "start_grade_level_season", "start_map_year_academic", "start_mean_npr",
    "start_mean_rit", "start_mean_testritscore", "start_n_50th_pctl",
    "start_n_75th_pctl", "start_percentile", "start_rit", "Start_Season",
    "start_testid", "start_testpercentile", "start_testquartile",
    "start_testquartile_format", "start_testritscore", "start_teststartdate",
    "stat_smooth", "stat_summary", "status_norms_2015", "status_ordered",
    "std_dev_of_expectation", "student_growth_norms_2011",
    "student_growth_norms_2015", "student_name_format", "student_percentile",
    "student_status_norms_2011", "student_status_norms_2011_dense_extended",
    "student_status_norms_2015_dense_extended", "studentfirstlast",
    "studentfirstlastrit", "studentfirstname", "studentfirstname.x",
    "studentfullname", "studentid", "StudentID", "studentids_gr11",
    "studentids_hs", "studentids_ms", "studentids_normal_use", "studentids_random",
    "studentids_subset", "studentlastfirst", "studentlastname",
    "studentlastname.x", "studentname", "Sub_Test_Name", "temp_year_season",
    "termname", "TermName", "test", "testid", "testpercentile", "TestPercentile",
    "testquartile", "testritscore", "testritscore.x", "testritscore.y",
    "teststandarderror.x", "teststandarderror.y", "teststartdate", "TestType",
    "text", "theme", "theme_bw", "theme_minimal", "tot", "total_cgi", "type",
    "typical_growth", "TypicalFallToFallGrowth", "TypicalFallToSpringGrowth",
    "TypicalFallToWinterGrowth", "TypicalSpringToSpringGrowth", "value",
    "variable", "WIPreviousAYSpring", "WISelectedAYFall", "x", "x_cgp",
    "x_pos", "xlab", "y", "y_cgp", "y_order", "y_val", "year_label",
    "year_sort", "year_y", "ylab", "ymax", "ymin", "yr")
)
